In [1]:
import sys
print("python : {}".format(sys.version))

import scipy
print("scipy : {}".format(scipy.__version__))

import pandas
print("pandas : {}".format(pandas.__version__))

import numpy
print("numpy : {}".format(numpy.__version__))

import matplotlib
print("matplotlib : {}".format(matplotlib.__version__))

import sklearn
print("sklearn : {}".format(sklearn.__version__))

python : 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
scipy : 1.6.0
pandas : 1.2.0
numpy : 1.19.3
matplotlib : 3.3.3
sklearn : 0.24.0


In [2]:
df = pandas.read_csv("Iris.csv")

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
x = df.iloc[:,1:5].values

In [5]:
y = df.iloc[:,5].values

In [6]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
labelencoder_y = LabelEncoder()

In [9]:
y = labelencoder_y.fit_transform(y)

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

## LOGISTIC REGRESSION

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

LogisticRegression()

In [16]:
y_pred = logmodel.predict(x_test)

In [17]:
y_pred


array([0, 0, 1, 1, 1, 2, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 0, 1, 2, 1, 1, 0,
       1, 2, 1, 2, 2, 2, 0, 2])

In [18]:
y_test

array([0, 0, 2, 1, 1, 2, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 0, 1, 1, 2, 1, 0,
       1, 2, 1, 2, 2, 2, 0, 2])

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
confusion_matrix(y_pred, y_test)

array([[ 7,  0,  0],
       [ 0,  8,  2],
       [ 0,  1, 12]], dtype=int64)

In [21]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [22]:
accuracy

90.0

## knn

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = "minkowski", p= 2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [24]:
y_pred = classifier_knn.predict(x_test)

In [25]:
confusion_matrix(y_test, y_pred)

array([[ 7,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 14]], dtype=int64)

In [26]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [27]:
accuracy

96.66666666666667

## naive bayes

In [28]:
from sklearn.naive_bayes import GaussianNB

In [29]:
classifier_nb = GaussianNB()

In [30]:
classifier_nb.fit(x_train, y_train)

GaussianNB()

In [31]:
y_pred = classifier_nb.predict(x_test)

In [32]:
y_pred

array([0, 0, 2, 1, 1, 2, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 0, 1, 2, 2, 1, 0,
       1, 2, 1, 2, 2, 2, 0, 2])

In [33]:
confusion_matrix(y_test, y_pred)

array([[ 7,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 14]], dtype=int64)

In [34]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [35]:
accuracy

96.66666666666667

# Support Vector Machine

## sigmoid

In [36]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel = "sigmoid")

In [37]:
classifier_svm_sigmoid.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [38]:
y_pred = classifier_svm_sigmoid.predict(x_test)

In [39]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
confusion_matrix(y_test, y_pred)

array([[ 7,  0,  0],
       [ 9,  0,  0],
       [14,  0,  0]], dtype=int64)

In [41]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [42]:
accuracy

23.333333333333332

## SVM linear

In [43]:
classifier_svm_linear = SVC(kernel = "linear")

In [44]:
classifier_svm_linear.fit(x_train, y_train)

SVC(kernel='linear')

In [45]:
y_pred = classifier_svm_linear.predict(x_test)

In [46]:
y_pred

array([0, 0, 2, 1, 1, 2, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 0, 1, 1, 2, 1, 0,
       1, 2, 1, 2, 2, 2, 0, 2])

In [47]:
confusion_matrix(y_pred, y_test)

array([[ 7,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 14]], dtype=int64)

In [48]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [49]:
accuracy

100.0

## RBF(radial basis function)

In [50]:
classifier_svm_rbf = SVC(kernel = "rbf")

In [51]:
classifier_svm_rbf.fit(x_train, y_train)

SVC()

In [52]:
y_pred = classifier_svm_rbf.predict(x_test)

In [53]:
confusion_matrix(y_pred, y_test)

array([[ 7,  0,  0],
       [ 0,  8,  2],
       [ 0,  1, 12]], dtype=int64)

In [54]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [55]:
accuracy

90.0

## Polynomial

In [56]:
classifier_svm_poly = SVC(kernel = "poly")

In [57]:
classifier_svm_poly.fit(x_train, y_train)

SVC(kernel='poly')

In [58]:
y_pred = classifier_svm_poly.predict(x_test)

In [59]:
confusion_matrix(y_pred, y_test)

array([[ 7,  0,  0],
       [ 0,  8,  0],
       [ 0,  1, 14]], dtype=int64)

In [60]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [61]:
accuracy

96.66666666666667

## decision tree

In [62]:
from sklearn.tree import DecisionTreeClassifier

In [63]:
classifier_dt = DecisionTreeClassifier(criterion = "entropy")

In [64]:
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [65]:
y_pred = classifier_dt.predict(x_test)

In [66]:
confusion_matrix(y_pred, y_test)

array([[ 7,  0,  0],
       [ 0,  8,  2],
       [ 0,  1, 12]], dtype=int64)

In [67]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [68]:
accuracy

90.0

## Random forest

In [69]:
from sklearn.ensemble import RandomForestClassifier

In [70]:
classifier_rf = RandomForestClassifier(n_estimators = 3, criterion = "entropy")

In [71]:
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [72]:
y_pred = classifier_rf.predict(x_test)

In [73]:
confusion_matrix(y_pred, y_test)

array([[ 7,  0,  0],
       [ 0,  8,  1],
       [ 0,  1, 13]], dtype=int64)

In [74]:
c_matrix = confusion_matrix(y_pred, y_test)

c_matrix_sum = 0
for i in range(len(c_matrix)):
    c_matrix_sum += sum(c_matrix[i])

accuracy = (c_matrix[0][0] + c_matrix[1][1] + c_matrix[2][2])/c_matrix_sum
accuracy = accuracy *100

In [75]:
accuracy

93.33333333333333